# Generated by Django 3.2.6 on 2021-08-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/blog.jpeg', null=True, upload_to='post/'),
        ),
    ]
